[package]
name = "gloss-word"
version = "0.1.6"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
edition = "2018"
categories = ["command-line-utilities"]
description = "A simple English dictionary lookup utility"
homepage = "https://github.com/theodore-s-beers/gloss-word"
keywords = ["definition", "dictionary", "etymology"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/theodore-s-beers/gloss-word"
exclude = ["og.png"]

[dependencies]
anyhow = "1.0.52"
clap = "2.34.0"
directories = "4.0.1"
indicatif = "0.16.2"
isahc = "1.6.0"
regex = "1.5.4"
scraper = "0.12.0"
tempfile = "3.2.0"
trash = "2.0.2"

[dependencies.rusqlite]
version = "0.26.3"
features = ["bundled"]

[[bin]]
name = "gloss"
path = "src/main.rs"
