[package]
name = "gloss-word"
version = "0.1.0"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
edition = "2018"
categories = ["command-line-utilities"]
description = "A simple English dictionary lookup utility"
homepage = "https://github.com/theodore-s-beers/gloss-word"
keywords = ["definition", "dictionary", "etymology"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/theodore-s-beers/gloss-word"

[dependencies]
anyhow = "1.0.40"
clap = "2.33.3"
directories = "3.0.1"
indicatif = "0.15.0"
isahc = "1.3.1"
regex = "1.4.5"
scraper = "0.12.0"
tempfile = "3.2.0"
trash = "2.0.0"

[dependencies.rusqlite]
version = "0.25.1"
features = ["bundled"]

[[bin]]
name = "gloss"
path = "src/main.rs"
