[package]
name = "gloss-word"
version = "0.2.1"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
edition = "2021"
categories = ["command-line-utilities"]
description = "A simple English dictionary lookup utility"
homepage = "https://github.com/theodore-s-beers/gloss-word"
keywords = ["definition", "dictionary", "etymology"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/theodore-s-beers/gloss-word"
exclude = ["og.png"]

[dependencies]
anyhow = "1.0.56"
directories = "4.0.1"
indicatif = "0.16.2"
isahc = "1.7.0"
regex = "1.5.5"
scraper = "0.12.0"
tempfile = "3.3.0"
trash = "2.0.4"

[dependencies.clap]
version = "3.1.7"
features = ["cargo"]

[dependencies.rusqlite]
version = "0.27.0"
features = ["bundled"]

[[bin]]
name = "gloss"
path = "src/main.rs"
