[package]
name = "gloss-word"
version = "0.2.8"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
edition = "2021"
categories = ["command-line-utilities"]
description = "A simple English dictionary lookup utility"
homepage = "https://github.com/theodore-s-beers/gloss-word"
keywords = ["definition", "dictionary", "etymology"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/theodore-s-beers/gloss-word"
exclude = ["og.png"]

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["cargo"] }
directories = "5.0.1"
indicatif = "0.17.7"
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["blocking"] }
rusqlite = { version = "0.31", features = ["bundled"] }
scraper = "0.18"
tempfile = "3.9.0"

[dependencies.trash]
version = "3.2.1"
default-features = false
features = ["coinit_apartmentthreaded"]

[[bin]]
name = "gloss"
path = "src/main.rs"
