[package]
name = "gloss-word"
version = "0.2.6"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
edition = "2021"
categories = ["command-line-utilities"]
description = "A simple English dictionary lookup utility"
homepage = "https://github.com/theodore-s-beers/gloss-word"
keywords = ["definition", "dictionary", "etymology"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/theodore-s-beers/gloss-word"
exclude = ["og.png"]

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.0", features = ["cargo"] }
directories = "5.0.1"
indicatif = "0.17.3"
regex = "1.8.2"
reqwest = { version = "0.11.18", features = ["blocking"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
scraper = "0.16.0"
tempfile = "3.5.0"

[dependencies.trash]
version = "3.0.2"
default-features = false
features = ["coinit_apartmentthreaded"]

[[bin]]
name = "gloss"
path = "src/main.rs"
