[package]
name = "gloss-word"
version = "0.2.2"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
edition = "2021"
categories = ["command-line-utilities"]
description = "A simple English dictionary lookup utility"
homepage = "https://github.com/theodore-s-beers/gloss-word"
keywords = ["definition", "dictionary", "etymology"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/theodore-s-beers/gloss-word"
exclude = ["og.png"]

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.8", features = ["cargo"] }
directories = "4.0.1"
indicatif = "0.16.2"
regex = "1.6.0"
reqwest = { version = "0.11.11", features = ["blocking"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
scraper = "0.13.0"
tempfile = "3.3.0"
trash = "2.1.5"

[[bin]]
name = "gloss"
path = "src/main.rs"
