[package]
name = "gloss-word"
version = "0.2.8"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
edition = "2021"
categories = ["command-line-utilities"]
description = "A simple English dictionary lookup utility"
homepage = "https://github.com/theodore-s-beers/gloss-word"
keywords = ["definition", "dictionary", "etymology"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/theodore-s-beers/gloss-word"
exclude = ["og.png"]

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["cargo"] }
directories = "5.0.1"
indicatif = "0.17.8"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["blocking"] }
rusqlite = { version = "0.31", features = ["bundled"] }
scraper = "0.19"
tempfile = "3.10.1"

[dependencies.trash]
version = "4.1.0"
default-features = false
features = ["coinit_apartmentthreaded"]

[[bin]]
name = "gloss"
path = "src/main.rs"
