[package]
name = "gloss-word"
version = "0.3.0"
authors = ["Theo Beers <theo.beers@drexel.edu>"]
edition = "2024"
categories = ["command-line-utilities"]
description = "A simple English dictionary lookup utility"
homepage = "https://github.com/theodore-s-beers/gloss-word"
keywords = ["definition", "dictionary", "etymology"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/theodore-s-beers/gloss-word"
exclude = ["og.png"]

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["cargo"] }
directories = "5.0.1"
indicatif = "0.17.9"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
rusqlite = { version = "0.32", features = ["bundled"] }
scraper = "0.22"
tempfile = "3.14.0"
trash = "5.2.1"

[[bin]]
name = "gloss"
path = "src/main.rs"
