[package]
name = "gloss-word"
version = "0.1.0"
authors = ["Theo Beers <theo.beers@fu-berlin.de>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
directories = "3.0.1"
isahc = "1.3.0"
regex = "1.4.5"
scraper = "0.12.0"
tempfile = "3.2.0"

[[bin]]
name = "gloss"
path = "src/main.rs"
