name: Test weekly

on:
  schedule:
    - cron: "0 12 * * 4"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Pandoc
        run: sudo apt install -y pandoc
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
